# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encdec.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import os
import main

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 800, 550))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tab.setFont(font)
        self.tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab.setAutoFillBackground(False)
        self.tab.setObjectName("tab")
        self.enc_tab = QtWidgets.QWidget()
        self.enc_tab.setObjectName("enc_tab")
        self.enc_edit = QtWidgets.QLineEdit(self.enc_tab)
        self.enc_edit.setGeometry(QtCore.QRect(210, 120, 391, 31))
        self.enc_edit.setObjectName("enc_edit")
        self.enc_label = QtWidgets.QLabel(self.enc_tab)
        self.enc_label.setGeometry(QtCore.QRect(70, 120, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.enc_label.sizePolicy().hasHeightForWidth())
        self.enc_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.enc_label.setFont(font)
        self.enc_label.setObjectName("enc_label")
        self.enc_button = QtWidgets.QPushButton(self.enc_tab)
        self.enc_button.setGeometry(QtCore.QRect(290, 280, 171, 61))
        self.enc_button.setObjectName("enc_button")
        self.enc_browse = QtWidgets.QPushButton(self.enc_tab)
        self.enc_browse.setGeometry(QtCore.QRect(660, 120, 90, 28))
        self.enc_browse.setObjectName("enc_browse")
        self.tab.addTab(self.enc_tab, "")
        self.dec_tab = QtWidgets.QWidget()
        self.dec_tab.setObjectName("dec_tab")
        self.dec_edit = QtWidgets.QLineEdit(self.dec_tab)
        self.dec_edit.setGeometry(QtCore.QRect(180, 110, 391, 31))
        self.dec_edit.setObjectName("dec_edit")
        self.dec_browse = QtWidgets.QPushButton(self.dec_tab)
        self.dec_browse.setGeometry(QtCore.QRect(630, 110, 90, 28))
        self.dec_browse.setObjectName("dec_browse")
        self.dec_label = QtWidgets.QLabel(self.dec_tab)
        self.dec_label.setGeometry(QtCore.QRect(50, 110, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.dec_label.sizePolicy().hasHeightForWidth())
        self.dec_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dec_label.setFont(font)
        self.dec_label.setObjectName("dec_label")
        self.key_edit = QtWidgets.QLineEdit(self.dec_tab)
        self.key_edit.setGeometry(QtCore.QRect(180, 190, 391, 31))
        self.key_edit.setObjectName("key_edit")
        self.key_browse = QtWidgets.QPushButton(self.dec_tab)
        self.key_browse.setGeometry(QtCore.QRect(630, 190, 90, 28))
        self.key_browse.setObjectName("key_browse")
        self.key_label = QtWidgets.QLabel(self.dec_tab)
        self.key_label.setGeometry(QtCore.QRect(50, 190, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.key_label.sizePolicy().hasHeightForWidth())
        self.key_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.key_label.setFont(font)
        self.key_label.setObjectName("key_label")
        self.dec_button = QtWidgets.QPushButton(self.dec_tab)
        self.dec_button.setGeometry(QtCore.QRect(300, 320, 171, 61))
        self.dec_button.setObjectName("dec_button")
        self.tab.addTab(self.dec_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.error=QtWidgets.QLabel(MainWindow)
        self.error.move(10,565)
        self.error.setText("Status : ")
        self.error.adjustSize()

        self.enc_browse.clicked.connect(self.browse_file_enc)
        self.dec_browse.clicked.connect(self.browse_file_dec)
        self.key_browse.clicked.connect(self.browse_file_key)
        self.enc_button.clicked.connect(self.encrypt)
        self.dec_button.clicked.connect(self.decrypt)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ENC-DEC"))
        self.enc_label.setText(_translate("MainWindow", "FILE"))
        self.enc_button.setText(_translate("MainWindow", "ENCRYPT"))
        self.enc_browse.setText(_translate("MainWindow", "BROWSE"))
        self.tab.setTabText(self.tab.indexOf(self.enc_tab), _translate("MainWindow", "ENCRYPT"))
        self.dec_browse.setText(_translate("MainWindow", "BROWSE"))
        self.dec_label.setText(_translate("MainWindow", "FILE"))
        self.key_browse.setText(_translate("MainWindow", "BROWSE"))
        self.key_label.setText(_translate("MainWindow", "KEY"))
        self.dec_button.setText(_translate("MainWindow", "DECRYPT"))
        self.tab.setTabText(self.tab.indexOf(self.dec_tab), _translate("MainWindow", "DECRYPT"))

   # dir_curr=os.path.dirname(os.path.realpath(__file__))
    dir_curr=os.getcwd()

    def browse_file_enc(self):
        self.error.setText("Status : ")
        br=QFileDialog.getOpenFileName(self.enc_tab, 'open file',self.dir_curr, 'text files(*.txt)')
        self.enc_edit.setText(br[0])

    def browse_file_dec(self):
        self.error.setText("Status : ")
        br=QFileDialog.getOpenFileName(self.dec_tab, 'open file', self.dir_curr, 'text files(*.txt)')
        self.dec_edit.setText(br[0])

    def browse_file_key(self):
        self.error.setText("Status : ")
        br=br=QFileDialog.getOpenFileName(self.dec_tab, 'open file', self.dir_curr, 'key files(*.key)')
        self.key_edit.setText(br[0])

    def encrypt(self):
        if not self.enc_edit.text():
            self.setStatus("Please input a file to encrypt")
            return
        try:
            main.encryptfile(self.enc_edit.text())
            self.setStatus("File successfully encrypted!")
        except FileNotFoundError:
            self.setStatus("File not found!")
            return
        except:
            self.setStatus("Unknown Error!")
            return
    def decrypt(self):
        if not self.dec_edit.text():
            self.setStatus("Please input a file to decrypt!")
            return
        elif not self.key_edit.text():
            self.setStatus("Please input a key file!")
            return
        try:
            main.decryptfile(self.dec_edit.text(),self.key_edit.text())
            self.setStatus("File successfully decrypted!")
        except FileNotFoundError:
            self.setStatus("File not found!")
            return
        except:
            self.setStatus("Unknown Error!")
            return

    def setStatus(self,err):
        self.error.setText('Status : '+err)
        self.error.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
